import { test, expect } from './fixtures';

test('desktop workflow: filters, download, page switching, cancellation, PDF and settings', async ({ page }) => {
  const failures: string[] = [];
  page.on('pageerror', error => failures.push(error.message));
  await page.goto('/');
  await expect(page.locator('[data-app-ready]')).toBeVisible();
  await expect(page.getByText('共 378 份報表')).toBeVisible();
  await page.getByLabel('報表類別').selectOption('消防');
  await page.getByLabel('名稱搜尋').fill('二門診滅火器');
  await expect(page.locator('.report-table:visible tbody tr')).toHaveCount(1);
  await page.getByRole('checkbox', { name: '選取目前清單的全部報表' }).check();
  await page.getByLabel('起始月份').fill('2026-01');
  await page.getByLabel('結束月份').fill('2026-02');
  await page.getByRole('button', { name: '開始下載' }).click();
  await expect(page.getByText('執行中', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: /PDF 擷取.*搜尋需要的頁面/ }).click();
  await expect(page.getByRole('heading', { name: 'PDF 擷取', exact: true })).toBeVisible();
  await expect(page.getByText('切換頁面不會中斷任務')).toBeVisible();
  await expect(page.getByText('已完成', { exact: true })).toBeVisible({ timeout: 10_000 });
  await page.getByRole('button', { name: /報表下載.*瀏覽與下載報表/ }).click();
  await expect(page.getByLabel('名稱搜尋')).toHaveValue('二門診滅火器');
  await page.getByLabel('起始月份').fill('2026-03');
  await page.getByLabel('結束月份').fill('2026-06');
  await page.getByRole('button', { name: '開始下載' }).click();
  await page.getByRole('button', { name: '取消任務' }).click();
  await expect(page.getByText('已取消', { exact: true }).first()).toBeVisible({ timeout: 10_000 });
  await page.getByRole('button', { name: /PDF 擷取.*搜尋需要的頁面/ }).click();
  await page.getByRole('button', { name: '選擇 PDF', exact: true }).click();
  await expect(page.getByText('sample.pdf', { exact: true })).toBeVisible();
  await page.getByLabel('搜尋關鍵字').fill('TARGET');
  await page.getByRole('button', { name: '開始擷取' }).click();
  await expect(page.getByText('已完成', { exact: true })).toBeVisible({ timeout: 10_000 });
  await expect(page.locator('.task-counts')).toContainText('成功 1');
  await page.getByRole('button', { name: /設定.*資料夾與偏好/ }).click();
  await page.getByRole('button', { name: '選擇報表下載資料夾', exact: true }).click();
  await expect(page.getByLabel('報表下載資料夾', { exact: true })).toHaveValue(/chosen-output/);
  await page.getByRole('checkbox', { name: /完成後開啟資料夾/ }).check();
  await page.getByRole('button', { name: '儲存設定' }).click();
  await expect(page.getByText('設定已儲存', { exact: true })).toBeVisible();
  await page.reload();
  await page.getByRole('button', { name: /設定.*資料夾與偏好/ }).click();
  await expect(page.getByLabel('報表下載資料夾', { exact: true })).toHaveValue(/chosen-output/);
  await expect(page.getByRole('checkbox', { name: /完成後開啟資料夾/ })).toBeChecked();
  expect(failures).toEqual([]);
});
